# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false
scan_timeout = 1000

[nodejs]
format = 'via [$symbol($version )](bold green) '

