unbind r
bind r source-file ~/.tmux.conf
set -g mouse on

set -g prefix C-s

set -g status-position bottom

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# act like vim
setw -g mode-keys vi
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# split panes using | and -
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

# Theme
set -g @plugin 'Nybkox/tmux-kanagawa'
set -g @kanagawa-theme 'dragon'
set -g @kanagawa-ignore-window-colors true
set -g @kanagawa-show-powerline true
set -g @kanagawa-show-edge-icons true
set -g @kanagawa-show-left-sep 
set -g @kanagawa-show-right-sep 
set -g @kanagawa-inverse-divider 
set -g @kanagawa-transparent-powerline-bg true
set -g @kanagawa-plugins "weather battery cpu-usage ram-usage"

run '~/.tmux/plugins/tpm/tpm'
